name: Windows build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        perl:
          - '5.32'
#           - '5.30'
#           - '5.28'
#           - '5.26'
#           - '5.24'
            
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
          # - '5.8'

    name: Perl ${{ matrix.perl }}
    steps:
      
    - uses: actions/checkout@v1
      
    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
        
    - name: Perl version
      run: perl -V
      
       
    # Install liblzma on windows
    - name: Install liblzma 
      run: |
        vcpkg install liblzma
        echo "::set-env name=VCPKG_INSTALLED::C:\vcpkg\installed"        
        echo "::set-env name=VCPKG_LIB::C:\vcpkg\installed\x86-windows\lib"
        echo "::set-env name=VCPKG_INC::C:\vcpkg\installed\x86-windows\include"

#     - name: find 
#       shell: bash
#       run: |
#         find /c/vcpkg
      
    
        
    - name: Install dependencies
      run: cpanm --quiet --installdeps --notest .
      
    - name: Build
      run: perl Makefile.PL INC="-I${{ env.VCPKG_INC }}" LIB="-L${{ env.VCPKG_LIB }}" && make
      
    - name: Test
      run: make test
