name: Windows build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        perl:
          - '5.32'
#           - '5.30'
#           - '5.28'
#           - '5.26'
#           - '5.24'
            
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
          # - '5.8'

    name: Perl ${{ matrix.perl }}
    steps:
      
    - uses: actions/checkout@v1
      
    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
        
    - name: Perl version
      run: perl -V
      
    - name: Set path
      shell: bash
      run: |
        echo "::set-env name=VCPKG_INSTALLED::$VCPKG_ROOT/installed"        
        echo "::set-env name=VCPKG_LIB::$VCPKG_ROOT/installed\$TRIPLET\lib"
        echo "::set-env name=VCPKG_INC::$VCPKG_ROOT/installed\$TRIPLET\include"
        
    # Install liblzma on windows
    - name: Install liblzma 
      shell: bash
      run: |
        vcpkg install liblzma
        echo VCPKG_INSTALLED $VCPKG_INSTALLED
        echo VCPKG_LIB $VCPKG_LIB
        echo VCPKG_INC $VCPKG_INC
        ls $VCPKG_INC        
    
        
    - name: Install dependencies
      shell: bash
      run: cpanm --quiet --installdeps --notest .
      
    - name: Build
      shell: bash
      run: perl Makefile.PL INC="-IVCPKG_INC" LIB="=L$VCPKG_LIB" && make
      
    - name: Test
      shell: bash
      run: make test
